
name = "ebook-simplicity-scribe-app"
compatibility_date = "2024-12-14"

[env.production]
name = "ebook-simplicity-scribe-production"

[[env.production.routes]]
pattern = "*"
zone_name = ""

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
dir = "dist"
main = "./dist/index.html"

[vars]
NODE_ENV = "production"
